const pokemon = [
  {
    dexID: "001",
    name: "Bulbasaur",
    type: ["grass", "poison"],
    abilities: ["overgrow", "chlorophyll"],
    desc: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger. While it is young, it uses the nutrients that are stored in the seed on its back in order to grow.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/1-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/001-back-n.gif",
    hp: "45",
    atk: "49",
    def: "49",
    spa: "65",
    spd: "65",
    speed: "45",
    evolutions: true,
    egg_groups: ["monster", "grass"],
    learnset: []
  },
  {
    dexID: "002",
    name: "Ivysaur",
    type: ["grass", "poison"],
    abilities: ["overgrow", "chlorophyll"],
    desc: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs. Exposure to sunlight adds to its strength. Sunlight also makes the bud on its back grow larger.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/2-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/002-back-n.gif",
    hp: "60",
    atk: "62",
    def: "63",
    spa: "80",
    spd: "80",
    speed: "60",
    evolutions: true,
    egg_groups: ["monster", "grass"],
    learnset: []
  },
  {
    dexID: "003",
    name: "Venusaur",
    type: ["grass", "poison"],
    abilities: ["overgrow", "chlorophyll"],
    desc: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight. A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/3-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/003-back-n.gif",
    hp: "80",
    atk: "82",
    def: "83",
    spa: "100",
    spd: "100",
    speed: "80",
    evolutions: false,
    egg_groups: ["monster", "grass"],
    learnset: []
  },
  {
    dexID: "004",
    name: "Charmander",
    type: ["fire"],
    abilities: ["blaze", "solar power"],
    desc: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail. From the time it is born, a flame burns at the tip of its tail. Its life would end if the flame were to go out.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/4-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/004-back-n.gif",
    hp: "39",
    atk: "52",
    def: "43",
    spa: "60",
    spd: "50",
    speed: "65",
    evolutions: true,
    egg_groups: ["dragon", "monster"],
    learnset: []
  },
  {
    dexID: "005",
    name: "Charmeleon",
    type: ["fire"],
    abilities: ["blaze", "solar power"],
    desc: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws. If it becomes agitated during battle, it spouts intense flames, incinerating its surroundings.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/5-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/005-back-n.gif",
    hp: "58",
    atk: "64",
    def: "58",
    spa: "80",
    spd: "65",
    speed: "80",
    evolutions: true,
    egg_groups: ["dragon", "monster"],
    learnset: []
  },
  {
    dexID: "006",
    name: "Charizard",
    type: ["fire", "flying"],
    abilities: ["blaze", "solar power"],
    desc: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames. Its wings can carry this Pokémon close to an altitude of 4,600 feet. It blows out fire at very high temperatures.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/6-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/006-back-n.gif",
    hp: "78",
    atk: "84",
    def: "78",
    spa: "109",
    spd: "85",
    speed: "100",
    evolutions: false,
    egg_groups: ["dragon", "monster"],
    learnset: ['flamethrower', 'dragon pulse']
  },
  {
    dexID: "007",
    name: "Squirtle",
    type: ["water"],
    abilities: ["torrent", "rain dish"],
    desc: "When it retracts its long neck into its shell, it squirts out water with vigorous force. When it feels threatened, it draws its limbs inside its shell and sprays water from its mouth.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/7-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/007-back-n.gif",
    hp: "44",
    atk: "48",
    def: "65",
    spa: "50",
    spd: "64",
    speed: "43",
    evolutions: true,
    egg_groups: ["monster", "water1"],
    learnset: []
  },
  {
    dexID: "008",
    name: "Wartortle",
    type: ["water"],
    abilities: ["torrent", "rain dish"],
    desc: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old. It cleverly controls its furry ears and tail to maintain its balance while swimming.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/8-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/008-back-n.gif",
    hp: "59",
    atk: "63",
    def: "80",
    spa: "65",
    spd: "80",
    speed: "58",
    evolutions: true,
    egg_groups: ["monster", "water1"],
    learnset: []
  },
  {
    dexID: "009",
    name: "Blastoise",
    type: ["water"],
    abilities: ["torrent", "rain dish"],
    desc: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell. The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/9-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/009-back-n.gif",
    hp: "79",
    atk: "83",
    def: "100",
    spa: "85",
    spd: "105",
    speed: "78",
    evolutions: false,
    egg_groups: ["monster", "water1"],
    learnset: []
  },
  {
    dexID: "010",
    name: "Caterpie",
    type: ["bug"],
    abilities: ["shield dust", "run away"],
    desc: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies. Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/10-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/010-back-n.gif",
    hp: "45",
    atk: "30",
    def: "35",
    spa: "20",
    spd: "20",
    speed: "45",
    evolutions: true,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "011",
    name: "Metapod",
    type: ["bug"],
    abilities: ["shed skin"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/11-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/011-back-n.gif",
    hp: "50",
    atk: "20",
    def: "55",
    spa: "25",
    spd: "25",
    speed: "30",
    evolutions: true,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "012",
    name: "Butterfree",
    type: ["bug", "flying"],
    abilities: ["compound eyes", "tinted lens"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/12-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/012-back-n.gif",
    hp: "60",
    atk: "45",
    def: "50",
    spa: "90",
    spd: "80",
    speed: "70",
    evolutions: false,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "013",
    name: "Weedle",
    type: ["bug", "poison"],
    abilities: ["shield dust", "run away"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/13-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/013-back-n.gif",
    hp: "40",
    atk: "35",
    def: "30",
    spa: "20",
    spd: "20",
    speed: "50",
    evolutions: true,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "014",
    name: "Kakuna",
    type: ["bug", "poison"],
    abilities: ["shed skin"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/14-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/014-back-n.gif",
    hp: "45",
    atk: "25",
    def: "50",
    spa: "25",
    spd: "25",
    speed: "35",
    evolutions: true,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "015",
    name: "Beedrill",
    type: ["bug", "poison"],
    abilities: ["swarm", "sniper"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/15-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/015-back-n.gif",
    hp: "65",
    atk: "90",
    def: "40",
    spa: "45",
    spd: "80",
    speed: "75",
    evolutions: false,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "016",
    name: "Pidgey",
    type: ["normal", "flying"],
    abilities: ["keen eye", "tangled feet", "big pecks"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/16-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/016-back-n.gif",
    hp: "40",
    atk: "45",
    def: "40",
    spa: "35",
    spd: "35",
    speed: "56",
    evolutions: true,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "017",
    name: "Pidgeotto",
    type: ["normal", "flying"],
    abilities: ["keen eye", "tangled feet", "big pecks"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/17-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/017-back-n.gif",
    hp: "63",
    atk: "60",
    def: "55",
    spa: "50",
    spd: "50",
    speed: "71",
    evolutions: true,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "018",
    name: "Pidgeot",
    type: ["normal", "flying"],
    abilities: ["keen eye", "tangled feet", "big pecks"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/18-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/018-back-n.gif",
    hp: "83",
    atk: "80",
    def: "75",
    spa: "70",
    spd: "70",
    speed: "101",
    evolutions: false,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "019",
    name: "Rattata",
    type: ["normal"],
    abilities: ["run away", "guts", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/19-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/019-back-n.gif",
    hp: "30",
    atk: "56",
    def: "35",
    spa: "25",
    spd: "35",
    speed: "72",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "020",
    name: "Raticate",
    type: ["normal"],
    abilities: ["run away", "guts", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/20-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/020-back-n.gif",
    hp: "55",
    atk: "81",
    def: "60",
    spa: "50",
    spd: "70",
    speed: "97",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "021",
    name: "Spearow",
    type: ["normal", "flying"],
    abilities: ["keen eye", "sniper"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/21-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/021-back-n.gif",
    hp: "40",
    atk: "60",
    def: "30",
    spa: "31",
    spd: "31",
    speed: "70",
    evolutions: true,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "022",
    name: "Fearow",
    type: ["normal", "flying"],
    abilities: ["keen eye", "sniper"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/22-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/022-back-n.gif",
    hp: "65",
    atk: "90",
    def: "65",
    spa: "61",
    spd: "61",
    speed: "100",
    evolutions: false,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "023",
    name: "Ekans",
    type: ["poison"],
    abilities: ["intimidate", "shed skin", "unnerve"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/23-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/023-back-n.gif",
    hp: "35",
    atk: "60",
    def: "44",
    spa: "40",
    spd: "54",
    speed: "55",
    evolutions: true,
    egg_groups: ["field", "dragon"],
    learnset: []
  },
  {
    dexID: "024",
    name: "Arbok",
    type: ["poison"],
    abilities: ["initimidate", "shed skin", "unnerve"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/24-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/024-back-n.gif",
    hp: "60",
    atk: "95",
    def: "69",
    spa: "65",
    spd: "79",
    speed: "80",
    evolutions: false,
    egg_groups: ["field", "dragon"],
    learnset: []
  },
  {
    dexID: "025",
    name: "Pikachu",
    type: ["electric"],
    abilities: ["static", "lightning rod"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/25-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/025-back-n.gif",
    hp: "35",
    atk: "55",
    def: "40",
    spa: "50",
    spd: "50",
    speed: "90",
    evolutions: true,
    egg_groups: ["field", "fairy"],
    learnset: []
  },
  {
    dexID: "026",
    name: "Raichu",
    type: ["electric"],
    abilities: ["static", "lightning rod"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/26-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/026-back-n.gif",
    hp: "60",
    atk: "90",
    def: "55",
    spa: "90",
    spd: "80",
    speed: "110",
    evolutions: false,
    egg_groups: ["field", "fairy"],
    learnset: []
  },
  {
    dexID: "027",
    name: "Sandshrew",
    type: ["ground"],
    abilities: ["sand veil", "sand rush"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/27-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/027-back-n.gif",
    hp: "50",
    atk: "75",
    def: "85",
    spa: "20",
    spd: "30",
    speed: "40",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "028",
    name: "Sandslash",
    type: ["ground"],
    abilities: ["sand veil", "sand rush"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/28-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/028-back-n.gif",
    hp: "75",
    atk: "100",
    def: "110",
    spa: "45",
    spd: "55",
    speed: "65",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "029",
    name: "Nidoran-F",
    type: ["poison"],
    abilities: ["poison point", "rivalry", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/29-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/029-back-n.gif",
    hp: "55",
    atk: "47",
    def: "52",
    spa: "40",
    spd: "40",
    speed: "41",
    evolutions: true,
    egg_groups: ["monster", "field"],
    learnset: []
  },
  {
    dexID: "030",
    name: "Nidorina",
    type: ["poison"],
    abilities: ["poison point", "rivalry", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/30-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/030-back-n.gif",
    hp: "70",
    atk: "62",
    def: "67",
    spa: "55",
    spd: "55",
    speed: "56",
    evolutions: true,
    egg_groups: ["UNDISCOVERED"],
    learnset: []
  },
  {
    dexID: "031",
    name: "Nidoqueen",
    type: ["poison", "ground"],
    abilities: ["poison point", "rivalry", "sheer force"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/31-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/031-back-n.gif",
    hp: "90",
    atk: "92",
    def: "87",
    spa: "75",
    spd: "85",
    speed: "76",
    evolutions: false,
    egg_groups: ["UNDISCOVERED"],
    learnset: []
  },
  {
    dexID: "032",
    name: "Nidoran-M",
    type: ["poison"],
    abilities: ["poison point", "rivalry", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/32-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/032-back-n.gif",
    hp: "46",
    atk: "57",
    def: "40",
    spa: "40",
    spd: "40",
    speed: "50",
    evolutions: true,
    egg_groups: ["monster", "field"],
    learnset: []
  },
  {
    dexID: "033",
    name: "Nidorino",
    type: ["poison"],
    abilities: ["poison point", "rivalry", "hustle"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/33-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/033-back-n.gif",
    hp: "61",
    atk: "72",
    def: "57",
    spa: "55",
    spd: "55",
    speed: "65",
    evolutions: false,
    egg_groups: ["monster", "field"],
    learnset: []
  },
  {
    dexID: "034",
    name: "Nidoking",
    type: ["poison", "ground"],
    abilities: ["poison point", "rivalry", "sheer force"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/34-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/035-back-n.gif",
    hp: "81",
    atk: "102",
    def: "77",
    spa: "85",
    spd: "75",
    speed: "85",
    evolutions: false,
    egg_groups: ["monster", "field"],
    learnset: []
  },
  {
    dexID: "035",
    name: "Clefairy",
    type: ["fairy"],
    abilities: ["cute charm", "magic guard", "friend guard"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/35-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/035-back-n.gif",
    hp: "70",
    atk: "45",
    def: "48",
    spa: "60",
    spd: "65",
    speed: "35",
    evolutions: true,
    egg_groups: ["fairy"],
    learnset: []
  },
  {
    dexID: "036",
    name: "Clefable",
    type: ["fairy"],
    abilities: ["cute charm", "magic guard", "unaware"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/36-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/036-back-n.gif",
    hp: "95",
    atk: "70",
    def: "73",
    spa: "95",
    spd: "90",
    speed: "60",
    evolutions: false,
    egg_groups: ["fairy"],
    learnset: []
  },
  {
    dexID: "037",
    name: "Vulpix",
    type: ["fire"],
    abilities: ["flash fire", "drought"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/37-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/037-back-n.gif",
    hp: "38",
    atk: "41",
    def: "40",
    spa: "50",
    spd: "65",
    speed: "65",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "038",
    name: "Ninetales",
    type: ["fire"],
    abilities: ["flash fire", "drought"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/38-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/039-back-n.gif",
    hp: "73",
    atk: "76",
    def: "75",
    spa: "81",
    spd: "100",
    speed: "100",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "039",
    name: "Jigglypuff",
    type: ["normal", "fairy"],
    abilities: ["cute charm", "competitive", "friend guard"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/39-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/039-back-n.gif",
    hp: "115",
    atk: "45",
    def: "20",
    spa: "45",
    spd: "25",
    speed: "20",
    evolutions: true,
    egg_groups: ["fairy"],
    learnset: []
  },
  {
    dexID: "040",
    name: "Wigglytuff",
    type: ["normal","fairy"],
    abilities: ["cute charm", "competitive", "frisk"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/40-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/040-back-n.gif",
    hp: "140",
    atk: "70",
    def: "45",
    spa: "85",
    spd: "50",
    speed: "45",
    evolutions: false,
    egg_groups: ["fairy"],
    learnset: []
  },
  {
    dexID: "041",
    name: "Zubat",
    type: ["poison", "flying"],
    abilities: ["inner focus", "infiltrator"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/41-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/041-back-n.gif",
    hp: "40",
    atk: "45",
    def: "35",
    spa: "30",
    spd: "40",
    speed: "55",
    evolutions: true,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "042",
    name: "Golbat",
    type: ["poison", "flying"],
    abilities: ["inner focus", "infiltrator"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/42-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/042-back-n.gif",
    hp: "75",
    atk: "80",
    def: "70",
    spa: "65",
    spd: "75",
    speed: "90",
    evolutions: true,
    egg_groups: ["flying"],
    learnset: []
  },
  {
    dexID: "043",
    name: "Oddish",
    type: ["grass", "poison"],
    abilities: ["chlorophyll", "run away"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/43-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/043-back-n.gif",
    hp: "45",
    atk: "50",
    def: "55",
    spa: "75",
    spd: "65",
    speed: "30",
    evolutions: true,
    egg_groups: ["grass"],
    learnset: []
  },
  {
    dexID: "044",
    name: "Gloom",
    type: ["grass", "poison"],
    abilities: ["chlorophyll", "stench"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/44-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/044-back-n.gif",
    hp: "60",
    atk: "65",
    def: "70",
    spa: "85",
    spd: "75",
    speed: "45",
    evolutions: true,
    egg_groups: ["grass"],
    learnset: []
  },
  {
    dexID: "045",
    name: "Vileplume",
    type: ["grass", "poison"],
    abilities: ["chlorophyll", "effect spore"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/45-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/045-back-n.gif",
    hp: "75",
    atk: "80",
    def: "85",
    spa: "110",
    spd: "90",
    speed: "50",
    evolutions: false,
    egg_groups: ["grass"],
    learnset: []
  },
  {
    dexID: "046",
    name: "Paras",
    type: ["bug", "grass"],
    abilities: ["effect spore", "dry skin", "damp"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/46-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/046-back-n.gif",
    hp: "35",
    atk: "70",
    def: "55",
    spa: "45",
    spd: "55",
    speed: "25",
    evolutions: true,
    egg_groups: ["bug", "grass"],
    learnset: []
  },
  {
    dexID: "047",
    name: "Parasect",
    type: ["bug", "grass"],
    abilities: ["effect spore", "dry skin", "damp"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/47-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/047-back-n.gif",
    hp: "60",
    atk: "95",
    def: "80",
    spa: "60",
    spd: "80",
    speed: "30",
    evolutions: false,
    egg_groups: ["bug", "grass"],
    learnset: []
  },
  {
    dexID: "048",
    name: "Venonat",
    type: ["bug", "poison"],
    abilities: ["compound eyes", "tinted lens", "run away"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/48-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/048-back-n.gif",
    hp: "60",
    atk: "55",
    def: "50",
    spa: "40",
    spd: "55",
    speed: "45",
    evolutions: true,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "049",
    name: "Venomoth",
    type: ["bug", "poison"],
    abilities: ["compound eyes", "tinted lens", "wonder skin"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/49-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/049-back-n.gif",
    hp: "70",
    atk: "65",
    def: "60",
    spa: "90",
    spd: "75",
    speed: "90",
    evolutions: false,
    egg_groups: ["bug"],
    learnset: []
  },
  {
    dexID: "050",
    name: "Diglett",
    type: ["ground"],
    abilities: ["sand veil", "arena trap", "sand force"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/50-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/050-back-n.gif",
    hp: "10",
    atk: "55",
    def: "25",
    spa: "35",
    spd: "45",
    speed: "95",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "051",
    name: "Dugtrio",
    type: ["ground"],
    abilities: ["sand veil", "arena trap", "sand force"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/51-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/051-back-n.gif",
    hp: "35",
    atk: "100",
    def: "50",
    spa: "50",
    spd: "70",
    speed: "110",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "052",
    name: "Meowth",
    type: ["normal"],
    abilities: ["pick up", "technician", "unnerve"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/52-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/052-back-n.gif",
    hp: "40",
    atk: "45",
    def: "35",
    spa: "40",
    spd: "40",
    speed: "90",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "053",
    name: "Persion",
    type: ["normal"],
    abilities: ["limber", "technician", "unnerve"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/53-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/053-back-n.gif",
    hp: "65",
    atk: "70",
    def: "60",
    spa: "65",
    spd: "65",
    speed: "115",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "054",
    name: "Psyduck",
    type: ["water"],
    abilities: ["damp", "cloud nine", "swift swim"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/54-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/054-back-n.gif",
    hp: "50",
    atk: "52",
    def: "48",
    spa: "65",
    spd: "50",
    speed: "55",
    evolutions: true,
    egg_groups: ["water1", "field"],
    learnset: []
  },
  {
    dexID: "055",
    name: "Golduck",
    type: ["water"],
    abilities: ["damp", "cloud nine", "swift swim"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/55-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/055-back-n.gif",
    hp: "80",
    atk: "82",
    def: "78",
    spa: "95",
    spd: "80",
    speed: "85",
    evolutions: false,
    egg_groups: ["water1", "field"],
    learnset: []
  },
  {
    dexID: "056",
    name: "Mankey",
    type: ["fighting"],
    abilities: ["vital spirit", "anger point", "defiant"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/56-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/056-back-n.gif",
    hp: "40",
    atk: "80",
    def: "35",
    spa: "35",
    spd: "45",
    speed: "70",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "057",
    name: "Primeape",
    type: ["fighting"],
    abilities: ["vital spirit", "anger point", "defiant"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/57-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/057-back-n.gif",
    hp: "65",
    atk: "105",
    def: "60",
    spa: "60",
    spd: "70",
    speed: "95",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "058",
    name: "Growlithe",
    type: ["fire"],
    abilities: ["intimidate", "flash fire", "justified"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/58-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/058-back-n.gif",
    hp: "55",
    atk: "70",
    def: "45",
    spa: "70",
    spd: "50",
    speed: "60",
    evolutions: true,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "059",
    name: "Arcanine",
    type: ["fire"],
    abilities: ["intimidate", "flash fire", "justified"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/59-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/059-back-n.gif",
    hp: "90",
    atk: "110",
    def: "80",
    spa: "100",
    spd: "80",
    speed: "95",
    evolutions: false,
    egg_groups: ["field"],
    learnset: []
  },
  {
    dexID: "060",
    name: "Poliwag",
    type: ["water"],
    abilities: ["water absorb", "damp", "swift swim"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/60-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/060-back-n.gif",
    hp: "40",
    atk: "50",
    def: "40",
    spa: "40",
    spd: "40",
    speed: "90",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "061",
    name: "Poliwhirl",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/61-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/061-back-n.gif",
    hp: "65",
    atk: "65",
    def: "65",
    spa: "50",
    spd: "50",
    speed: "90",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "062",
    name: "Poliwrath",
    type: ["water", "fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/62-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/062-back-n.gif",
    hp: "90",
    atk: "95",
    def: "95",
    spa: "70",
    spd: "90",
    speed: "70",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "063",
    name: "Abra",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/63-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/063-back-n.gif",
    hp: "25",
    atk: "20",
    def: "15",
    spa: "105",
    spd: "55",
    speed: "90",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "064",
    name: "Kadabra",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/64-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/064-back-n.gif",
    hp: "40",
    atk: "35",
    def: "30",
    spa: "120",
    spd: "70",
    speed: "105",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "065",
    name: "Alakazam",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/65-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/065-back-n.gif",
    hp: "55",
    atk: "50",
    def: "45",
    spa: "135",
    spd: "95",
    speed: "120",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "066",
    name: "Machop",
    type: ["fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/66-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/066-back-n.gif",
    hp: "70",
    atk: "80",
    def: "50",
    spa: "35",
    spd: "35",
    speed: "35",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "067",
    name: "Machoke",
    type: ["fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/67-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/067-back-n.gif",
    hp: "80",
    atk: "100",
    def: "70",
    spa: "50",
    spd: "60",
    speed: "45",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "068",
    name: "Machamp",
    type: ["fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/68-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/068-back-n.gif",
    hp: "90",
    atk: "130",
    def: "80",
    spa: "65",
    spd: "85",
    speed: "55",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "069",
    name: "Bellsprout",
    type: ["grass", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/69-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/069-back-n.gif",
    hp: "50",
    atk: "75",
    def: "35",
    spa: "70",
    spd: "30",
    speed: "40",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "070",
    name: "Weepinbell",
    type: ["grass", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/70-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/070-back-n.gif",
    hp: "65",
    atk: "90",
    def: "50",
    spa: "85",
    spd: "45",
    speed: "44",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "071",
    name: "Victreebel",
    type: ["grass", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/71-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/071-back-n.gif",
    hp: "80",
    atk: "105",
    def: "65",
    spa: "100",
    spd: "70",
    speed: "70",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "072",
    name: "Tentacool",
    type: ["water", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/72-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/072-back-n.gif",
    hp: "40",
    atk: "40",
    def: "35",
    spa: "50",
    spd: "100",
    speed: "70",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "073",
    name: "Tentacruel",
    type: ["water", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/73-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/073-back-n.gif",
    hp: "80",
    atk: "70",
    def: "65",
    spa: "80",
    spd: "120",
    speed: "100",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "074",
    name: "Geodude",
    type: ["rock", "ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/74-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/074-back-n.gif",
    hp: "40",
    atk: "80",
    def: "100",
    spa: "30",
    spd: "30",
    speed: "20",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "075",
    name: "Graveler",
    type: ["rock", "ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/75-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/075-back-n.gif",
    hp: "55",
    atk: "95",
    def: "115",
    spa: "45",
    spd: "45",
    speed: "35",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "076",
    name: "Golem",
    type: ["rock", "ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/76-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/076-back-n.gif",
    hp: "80",
    atk: "120",
    def: "130",
    spa: "55",
    spd: "65",
    speed: "45",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "077",
    name: "Ponyta",
    type: ["fire"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/77-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/077-back-n.gif",
    hp: "50",
    atk: "85",
    def: "55",
    spa: "65",
    spd: "65",
    speed: "90",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "078",
    name: "Rapidash",
    type: ["fire"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/78-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/078-back-n.gif",
    hp: "65",
    atk: "100",
    def: "70",
    spa: "80",
    spd: "80",
    speed: "105",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "079",
    name: "Slowpoke",
    type: ["water", "psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/79-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/079-back-n.gif",
    hp: "90",
    atk: "65",
    def: "65",
    spa: "40",
    spd: "40",
    speed: "15",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "080",
    name: "Slowbro",
    type: ["water", "psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/80-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/080-back-n.gif",
    hp: "95",
    atk: "75",
    def: "110",
    spa: "100",
    spd: "80",
    speed: "30",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "081",
    name: "Magnemite",
    type: ["electric", "steel"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/81-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/081-back-n.gif",
    hp: "25",
    atk: "35",
    def: "70",
    spa: "95",
    spd: "55",
    speed: "45",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "082",
    name: "Magneton",
    type: ["electric", "steel"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/82-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/082-back-n.gif",
    hp: "50",
    atk: "60",
    def: "95",
    spa: "120",
    spd: "70",
    speed: "70",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "083",
    name: "Farfetch'd",
    type: ["normal", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/83-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/083-back-n.gif",
    hp: "52",
    atk: "90",
    def: "55",
    spa: "58",
    spd: "62",
    speed: "60",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "084",
    name: "Doduo",
    type: ["normal", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/84-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/084-back-n.gif",
    hp: "35",
    atk: "85",
    def: "45",
    spa: "35",
    spd: "35",
    speed: "75",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "085",
    name: "Dodrio",
    type: ["normal", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/85-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/085-back-n.gif",
    hp: "60",
    atk: "110",
    def: "70",
    spa: "60",
    spd: "60",
    speed: "110",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "086",
    name: "Seel",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/86-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/086-back-n.gif",
    hp: "65",
    atk: "45",
    def: "55",
    spa: "45",
    spd: "70",
    speed: "45",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "087",
    name: "Dewgong",
    type: ["water", "ice"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/87-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/087-back-n.gif",
    hp: "90",
    atk: "70",
    def: "80",
    spa: "70",
    spd: "95",
    speed: "70",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "088",
    name: "Grimer",
    type: ["poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/88-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/088-back-n.gif",
    hp: "80",
    atk: "80",
    def: "50",
    spa: "40",
    spd: "50",
    speed: "25",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "089",
    name: "Muk",
    type: ["poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/89-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/089-back-n.gif",
    hp: "105",
    atk: "105",
    def: "75",
    spa: "65",
    spd: "100",
    speed: "50",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "090",
    name: "Shellder",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/90-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/090-back-n.gif",
    hp: "30",
    atk: "65",
    def: "100",
    spa: "45",
    spd: "25",
    speed: "40",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "091",
    name: "Cloyster",
    type: ["water", "ice"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/91-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/091-back-n.gif",
    hp: "50",
    atk: "95",
    def: "180",
    spa: "85",
    spd: "45",
    speed: "70",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "092",
    name: "Gastly",
    type: ["ghost", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/92-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/092-back-n.gif",
    hp: "30",
    atk: "35",
    def: "30",
    spa: "100",
    spd: "35",
    speed: "80",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "093",
    name: "Haunter",
    type: ["ghost", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/93-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/093-back-n.gif",
    hp: "45",
    atk: "50",
    def: "45",
    spa: "115",
    spd: "55",
    speed: "95",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "094",
    name: "Gengar",
    type: ["ghost", "poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/94-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/094-back-n.gif",
    hp: "60",
    atk: "65",
    def: "60",
    spa: "130",
    spd: "75",
    speed: "110",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "095",
    name: "Onix",
    type: ["rock", "ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/95-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/095-back-n.gif",
    hp: "35",
    atk: "45",
    def: "160",
    spa: "30",
    spd: "45",
    speed: "70",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "096",
    name: "Drowzee",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/96-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/096-back-n.gif",
    hp: "60",
    atk: "48",
    def: "45",
    spa: "43",
    spd: "90",
    speed: "42",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "097",
    name: "Hypno",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/97-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/097-back-n.gif",
    hp: "85",
    atk: "73",
    def: "70",
    spa: "73",
    spd: "115",
    speed: "67",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "098",
    name: "Krabby",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/98-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/098-back-n.gif",
    hp: "30",
    atk: "105",
    def: "90",
    spa: "25",
    spd: "25",
    speed: "50",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "099",
    name: "Kingler",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/99-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/099-back-n.gif",
    hp: "55",
    atk: "130",
    def: "115",
    spa: "50",
    spd: "50",
    speed: "75",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "100",
    name: "Voltorb",
    type: ["electric"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/100-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/100-back-n.gif",
    hp: "40",
    atk: "30",
    def: "50",
    spa: "55",
    spd: "55",
    speed: "100",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "101",
    name: "Electrode",
    type: ["electric"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/101-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/101-back-n.gif",
    hp: "60",
    atk: "50",
    def: "70",
    spa: "80",
    spd: "80",
    speed: "150",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "102",
    name: "Exeggcute",
    type: ["grass", "psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/102-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/102-back-n.gif",
    hp: "60",
    atk: "40",
    def: "80",
    spa: "60",
    spd: "45",
    speed: "40",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "103",
    name: "Exeggutor",
    type: ["grass", "psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/103-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/103-back-n.gif",
    hp: "95",
    atk: "95",
    def: "85",
    spa: "125",
    spd: "75",
    speed: "55",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "104",
    name: "Cubone",
    type: ["ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/104-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/104-back-n.gif",
    hp: "50",
    atk: "50",
    def: "95",
    spa: "40",
    spd: "50",
    speed: "35",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "105",
    name: "Marowak",
    type: ["ground"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/105-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/105-back-n.gif",
    hp: "60",
    atk: "80",
    def: "110",
    spa: "50",
    spd: "80",
    speed: "45",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "106",
    name: "Hitmonlee",
    type: ["fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/106-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/106-back-n.gif",
    hp: "50",
    atk: "120",
    def: "53",
    spa: "35",
    spd: "110",
    speed: "87",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "107",
    name: "Hitmonchan",
    type: ["fighting"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/107-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/107-back-n.gif",
    hp: "50",
    atk: "105",
    def: "79",
    spa: "35",
    spd: "110",
    speed: "76",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "108",
    name: "Lickitung",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/108-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/108-back-n.gif",
    hp: "90",
    atk: "55",
    def: "75",
    spa: "60",
    spd: "75",
    speed: "30",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "109",
    name: "Koffing",
    type: ["poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/109-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/109-back-n.gif",
    hp: "40",
    atk: "65",
    def: "95",
    spa: "60",
    spd: "75",
    speed: "30",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "110",
    name: "Weezing",
    type: ["poison"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/110-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/110-back-n.gif",
    hp: "65",
    atk: "90",
    def: "120",
    spa: "85",
    spd: "70",
    speed: "60",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "111",
    name: "Rhyhorn",
    type: ["ground", "rock"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/111-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/111-back-n.gif",
    hp: "80",
    atk: "85",
    def: "95",
    spa: "30",
    spd: "30",
    speed: "25",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "112",
    name: "Rhydon",
    type: ["ground", "rock"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/112-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/112-back-n.gif",
    hp: "105",
    atk: "130",
    def: "120",
    spa: "45",
    spd: "45",
    speed: "40",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "113",
    name: "Chansey",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/113-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/113-back-n.gif",
    hp: "250",
    atk: "5",
    def: "5",
    spa: "35",
    spd: "105",
    speed: "50",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "114",
    name: "Tangela",
    type: ["grass"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/114-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/114-back-n.gif",
    hp: "65",
    atk: "55",
    def: "115",
    spa: "100",
    spd: "40",
    speed: "60",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "115",
    name: "Kangaskhan",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/115-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/115-back-n.gif",
    hp: "105",
    atk: "95",
    def: "80",
    spa: "40",
    spd: "80",
    speed: "90",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "116",
    name: "Horsea",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/116-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/116-back-n.gif",
    hp: "30",
    atk: "40",
    def: "70",
    spa: "70",
    spd: "25",
    speed: "60",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "117",
    name: "Seadra",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/117-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/117-back-n.gif",
    hp: "55",
    atk: "65",
    def: "95",
    spa: "95",
    spd: "45",
    speed: "85",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "118",
    name: "Goldeen",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/118-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/118-back-n.gif",
    hp: "45",
    atk: "67",
    def: "60",
    spa: "35",
    spd: "50",
    speed: "63",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "119",
    name: "Seaking",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/119-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/119-back-n.gif",
    hp: "80",
    atk: "92",
    def: "65",
    spa: "65",
    spd: "80",
    speed: "68",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "120",
    name: "Staryu",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/120-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/120-back-n.gif",
    hp: "30",
    atk: "45",
    def: "55",
    spa: "70",
    spd: "55",
    speed: "85",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "121",
    name: "Starmie",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/121-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/121-back-n.gif",
    hp: "60",
    atk: "75",
    def: "85",
    spa: "100",
    spd: "85",
    speed: "115",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "122",
    name: "Mr.Mime",
    type: ["psychic", "fairy"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/122-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/122-back-n.gif",
    hp: "40",
    atk: "45",
    def: "65",
    spa: "100",
    spd: "85",
    speed: "90",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "123",
    name: "Scyther",
    type: ["bug", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/123-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/123-back-n.gif",
    hp: "70",
    atk: "110",
    def: "80",
    spa: "55",
    spd: "80",
    speed: "105",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "124",
    name: "Jynx",
    type: ["ice", "psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/124-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/124-back-n.gif",
    hp: "65",
    atk: "50",
    def: "35",
    spa: "115",
    spd: "95",
    speed: "95",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "125",
    name: "Electabuzz",
    type: ["electric"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/125-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/125-back-n.gif",
    hp: "65",
    atk: "83",
    def: "57",
    spa: "95",
    spd: "85",
    speed: "105",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "126",
    name: "Magmar",
    type: ["fire"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/126-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/126-back-n.gif",
    hp: "65",
    atk: "95",
    def: "57",
    spa: "100",
    spd: "85",
    speed: "93",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "127",
    name: "Pinsir",
    type: ["bug"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/127-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/127-back-n.gif",
    hp: "65",
    atk: "125",
    def: "100",
    spa: "55",
    spd: "70",
    speed: "85",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "128",
    name: "Tauros",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/128-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/128-back-n.gif",
    hp: "75",
    atk: "100",
    def: "95",
    spa: "40",
    spd: "70",
    speed: "110",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "129",
    name: "Magikarp",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/29-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/129-back-n.gif",
    hp: "20",
    atk: "10",
    def: "55",
    spa: "15",
    spd: "20",
    speed: "80",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "130",
    name: "Gyarados",
    type: ["water", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/130-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/130-back-n.gif",
    hp: "95",
    atk: "125",
    def: "79",
    spa: "60",
    spd: "100",
    speed: "81",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "131",
    name: "Lapras",
    type: ["water", "ice"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/131-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/131-back-n.gif",
    hp: "130",
    atk: "85",
    def: "80",
    spa: "85",
    spd: "95",
    speed: "60",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "132",
    name: "Ditto",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/132-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/132-back-n.gif",
    hp: "48",
    atk: "48",
    def: "48",
    spa: "48",
    spd: "48",
    speed: "48",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "133",
    name: "Eevee",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/133-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/133-back-n.gif",
    hp: "55",
    atk: "55",
    def: "50",
    spa: "45",
    spd: "65",
    speed: "55",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "134",
    name: "Vaporeon",
    type: ["water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/134-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/134-back-n.gif",
    hp: "130",
    atk: "65",
    def: "60",
    spa: "110",
    spd: "95",
    speed: "65",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "135",
    name: "Jolteon",
    type: ["electric"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/135-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/135-back-n.gif",
    hp: "65",
    atk: "65",
    def: "60",
    spa: "110",
    spd: "95",
    speed: "130",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "136",
    name: "Flareon",
    type: ["fire"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/136-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/136-back-n.gif",
    hp: "65",
    atk: "130",
    def: "60",
    spa: "95",
    spd: "110",
    speed: "65",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "137",
    name: "Porygon",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/137-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/137-back-n.gif",
    hp: "65",
    atk: "60",
    def: "70",
    spa: "85",
    spd: "75",
    speed: "40",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "138",
    name: "Omanyte",
    type: ["rock", "water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/138-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/138-back-n.gif",
    hp: "35",
    atk: "40",
    def: "100",
    spa: "90",
    spd: "55",
    speed: "35",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "139",
    name: "Omastar",
    type: ["rock", "water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/139-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/139-back-n.gif",
    hp: "70",
    atk: "60",
    def: "125",
    spa: "115",
    spd: "70",
    speed: "55",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "140",
    name: "Kabuto",
    type: ["rock", "water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/140-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/140-back-n.gif",
    hp: "30",
    atk: "80",
    def: "90",
    spa: "55",
    spd: "45",
    speed: "55",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "141",
    name: "Kabutops",
    type: ["rock", "water"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/141-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/141-back-n.gif",
    hp: "60",
    atk: "115",
    def: "105",
    spa: "65",
    spd: "70",
    speed: "80",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "142",
    name: "Aerodactly",
    type: ["rock", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/142-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/142-back-n.gif",
    hp: "80",
    atk: "105",
    def: "65",
    spa: "60",
    spd: "75",
    speed: "130",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "143",
    name: "Snorlax",
    type: ["normal"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/143-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/143-back-n.gif",
    hp: "160",
    atk: "110",
    def: "65",
    spa: "65",
    spd: "110",
    speed: "30",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "144",
    name: "Articuno",
    type: ["ice", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/144-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/144-back-n.gif",
    hp: "90",
    atk: "85",
    def: "100",
    spa: "95",
    spd: "125",
    speed: "85",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "145",
    name: "Zapdos",
    type: ["electric", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/145-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/145-back-n.gif",
    hp: "90",
    atk: "90",
    def: "85",
    spa: "125",
    spd: "90",
    speed: "100",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "146",
    name: "Moltres",
    type: ["fire", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/146-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/146-back-n.gif",
    hp: "90",
    atk: "100",
    def: "90",
    spa: "125",
    spd: "85",
    speed: "90",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "147",
    name: "Dratini",
    type: ["dragon"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/147-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/147-back-n.gif",
    hp: "41",
    atk: "64",
    def: "45",
    spa: "50",
    spd: "50",
    speed: "50",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "148",
    name: "Dragonair",
    type: ["dragon"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/148-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/148-back-n.gif",
    hp: "61",
    atk: "84",
    def: "65",
    spa: "70",
    spd: "70",
    speed: "70",
    evolutions: true,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "149",
    name: "Dragonite",
    type: ["dragon", "flying"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/149-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/149-back-n.gif",
    hp: "91",
    atk: "134",
    def: "95",
    spa: "100",
    spd: "100",
    speed: "80",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "150",
    name: "Mewtwo",
    type: ["psychic"],
    abilities: [],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/150-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/150-back-n.gif",
    hp: "106",
    atk: "110",
    def: "90",
    spa: "154",
    spd: "90",
    speed: "130",
    evolutions: false,
    egg_groups: [],
    learnset: []
  },
  {
    dexID: "151",
    name: "Mew",
    type: ["psychic"],
    abilities: ["syncronize"],
    desc: "",
    sprite: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/151-front-n.gif",
    back: "https://raw.githubusercontent.com/Dan-Koyuki/Image-Pokemon_Sprite/master/151-back-n.gif",
    hp: "100",
    atk: "100",
    def: "100",
    spa: "100",
    spd: "100",
    speed: "100",
    evolutions: false,
    egg_groups: ["UNDISCOVERED"],
    learnset: []
  }
]

module.exports = pokemon;