const Teams = [
  {
    TeamID: "Test01",
    Member : [
      {
        name: "Charizard",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Flamethrower", "Air Slash", "Solar Beam", "Scorching Sands"],
      }, 
      {
        name: "Venusaur",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Sludge Bomb", "Giga Drain", "Earth Power", "Weather Ball"]
      },
      {
        name: "Blastoise",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Hydro Pump", "Rapid Spin", "Ice Beam", "Dark Pulse"]
      },
      {
        name: "Pikachu",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 252,
        evDEF: 0,
        evSPA: 0,
        evSPD: 0,
        evSPE: 252,
        moves: ["Volt Tackle", "Surf", "Volt Switch", "Extreme Speed"]
      }, 
      {
        name: "Snorlax",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 252,
        evATK: 0,
        evDEF: 168,
        evSPA: 0,
        evSPD: 90,
        evSPE: 0,
        moves: ["Body Slam", "Fire Punch", "Thunder Punch", "Ice Punch"]
      },
      {
        name: "Articuno",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Freeze-Dry", "Air Slash", "Hurricane", "Freezing Glare"]
      }
    ]
  },
  {
    TeamID: "Test02",
    Member : [
      {
        name: "Gyarados",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 252,
        evDEF: 0,
        evSPA: 0,
        evSPD: 0,
        evSPE: 252,
        moves: ["Earthquake", "Waterfall", "Bounce", "Crunch"]
      }, 
      {
        name: "Dragonite",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 200,
        evDEF: 0,
        evSPA: 52,
        evSPD: 0,
        evSPE: 252,
        moves: ["Draco Meteor", "Outrage", "Earthquake", "Extreme Speed"]
      },
      {
        name: "Aerodactly",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 252,
        evDEF: 0,
        evSPA: 0,
        evSPD: 0,
        evSPE: 252,
        moves: ["Rock Slide", "Aerial Ace", "Earthquake", "Stone Edge"]
      },
      {
        name: "Zapdos",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Hurricane", "Thunder", "Volt Switch", "Heat Wave"]
      }, 
      {
        name: "Moltres",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 0,
        evATK: 0,
        evDEF: 4,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Fire Blast", "Hurricane", "Extrasensory", "Burn Up"]
      },
      {
        name: "Articuno",
        level: 100,
        ivHP: 31,
        ivATK: 31,
        ivDEF: 31,
        ivSPA: 31,
        ivSPD: 31,
        ivSPE: 31,
        evHP: 4,
        evATK: 0,
        evDEF: 0,
        evSPA: 252,
        evSPD: 0,
        evSPE: 252,
        moves: ["Freeze-Dry", "Air Slash", "Hurricane", "Freezing Glare"]
      }
    ]
  }
]

module.exports = Teams